package com.amalskr.prodcheck.agent

import kotlinx.serialization.json.*
import java.io.File

/**
 * AUTO-FIX MODE.
 *
 * Design choice: the agent does NOT emit unified diffs directly — LLM-generated
 * diffs frequently have wrong line numbers/context and fail `git apply`.
 * Instead it proposes edits through a `propose_edit(path, old_str, new_str)` tool,
 * where old_str must match the file content EXACTLY and UNIQUELY. Each edit is
 * validated at proposal time; on failure the agent gets the error back and retries.
 *
 * The validated edits are then turned into a real unified diff (generated by us,
 * not the model) at build/reports/prodcheck-fix.patch, appliable with:
 *
 *     git apply build/reports/prodcheck-fix.patch
 *
 * With --apply-fixes the edits are written straight to the working tree instead
 * (safe because the tree is git-tracked: review with `git diff`, undo with
 * `git checkout -- <file>`).
 */

private val FIX_SYSTEM_PROMPT = """
You are ProdCheck-Fixer. You receive a list of production-readiness findings for an
Android (Kotlin) codebase. Produce MINIMAL, surgical fixes.

Rules:
- Fix only "blocker" and "warning" findings. Skip "info".
- Use read_file to see the current file content BEFORE proposing any edit.
- Propose each change with propose_edit. old_str must be copied character-for-character
  from the file and must appear exactly once (include surrounding lines for uniqueness).
- Do not refactor, rename, reformat, or "improve" anything beyond the finding.
- Preserve the file's existing indentation style exactly.
- If a fix requires a new import, propose a separate edit that adds it next to the
  existing imports.
- If a finding cannot be fixed safely without more context (e.g. needs a product
  decision), skip it and say why in your final summary.

When all edits are proposed, reply with a short plain-text summary of what you fixed
and what you skipped. No JSON needed.
""".trimIndent()

private data class Edit(val path: String, val oldStr: String, val newStr: String)

class FixMode(private val client: AnthropicClient, private val repoRoot: File) {

    private val edits = mutableListOf<Edit>()

    private val tools: JsonArray = buildJsonArray {
        RepoTools.definitions.forEach { add(it) }   // read_file, find_files
        add(buildJsonObject {
            put("name", "propose_edit")
            put("description",
                "Propose a fix. old_str must match the file content exactly and occur " +
                "exactly once. Returns OK or a validation error you must correct.")
            put("input_schema", buildJsonObject {
                put("type", "object")
                put("properties", buildJsonObject {
                    put("path", buildJsonObject { put("type", "string") })
                    put("old_str", buildJsonObject { put("type", "string") })
                    put("new_str", buildJsonObject { put("type", "string") })
                    put("reason", buildJsonObject { put("type", "string") })
                })
                put("required", buildJsonArray { add("path"); add("old_str"); add("new_str") })
            })
        })
    }

    private fun executeTool(name: String, input: JsonObject): String {
        if (name != "propose_edit") return RepoTools.execute(name, input)

        val path = input["path"]!!.jsonPrimitive.content
        val oldStr = input["old_str"]!!.jsonPrimitive.content
        val newStr = input["new_str"]!!.jsonPrimitive.content
        val file = repoRoot.resolve(path).canonicalFile

        if (!file.path.startsWith(repoRoot.canonicalPath)) return "ERROR: path escapes repo root"
        if (!file.exists()) return "ERROR: file not found: $path"

        // Validate against content WITH earlier accepted edits already applied,
        // so sequential edits to the same file stay consistent.
        val current = contentWithEdits(path, file.readText())
            ?: return "ERROR: an earlier edit to this file no longer applies"
        val occurrences = current.split(oldStr).size - 1
        return when {
            occurrences == 0 -> "ERROR: old_str not found. Re-read the file and copy exactly."
            occurrences > 1 -> "ERROR: old_str occurs $occurrences times. Add surrounding lines to make it unique."
            else -> {
                edits += Edit(path, oldStr, newStr)
                "OK — edit #${edits.size} recorded for $path"
            }
        }
    }

    private fun contentWithEdits(path: String, original: String): String? {
        var text = original
        edits.filter { it.path == path }.forEach {
            if (!text.contains(it.oldStr)) return null
            text = text.replace(it.oldStr, it.newStr)
        }
        return text
    }

    fun run(findings: JsonArray, applyDirectly: Boolean) {
        println("\n--- Auto-fix mode ---")
        val fixable = findings.filter {
            it.jsonObject["severity"]?.jsonPrimitive?.content in setOf("blocker", "warning")
        }
        if (fixable.isEmpty()) { println("No blocker/warning findings to fix."); return }

        val messages = buildJsonArray {
            add(buildJsonObject {
                put("role", "user")
                put("content", "FINDINGS TO FIX:\n" +
                    Json { prettyPrint = true }.encodeToString(JsonArray.serializer(), JsonArray(fixable)))
            })
        }.toMutableList()

        var summary = "(no summary)"
        for (turn in 1..MAX_AGENT_TURNS) {
            val response = client.call(FIX_SYSTEM_PROMPT, JsonArray(messages), tools)
            val content = response["content"]!!.jsonArray
            messages += buildJsonObject { put("role", "assistant"); put("content", content) }

            if (response["stop_reason"]?.jsonPrimitive?.content == "tool_use") {
                val results = buildJsonArray {
                    content.filter { it.jsonObject["type"]?.jsonPrimitive?.content == "tool_use" }
                        .forEach { block ->
                            val b = block.jsonObject
                            val name = b["name"]!!.jsonPrimitive.content
                            println("  fixer -> $name")
                            add(buildJsonObject {
                                put("type", "tool_result")
                                put("tool_use_id", b["id"]!!.jsonPrimitive.content)
                                put("content", executeTool(name, b["input"]!!.jsonObject))
                            })
                        }
                }
                messages += buildJsonObject { put("role", "user"); put("content", results) }
            } else {
                summary = content
                    .filter { it.jsonObject["type"]?.jsonPrimitive?.content == "text" }
                    .joinToString("") { it.jsonObject["text"]!!.jsonPrimitive.content }
                break
            }
        }

        if (edits.isEmpty()) { println("Fixer proposed no edits.\n$summary"); return }

        if (applyDirectly) {
            applyToWorkingTree()
            println("Applied ${edits.size} edit(s) to the working tree. " +
                "Review with `git diff`, undo with `git checkout -- <file>`.")
        } else {
            val patch = generatePatch()
            val patchFile = File(repoRoot, "build/reports/prodcheck-fix.patch")
            patchFile.parentFile.mkdirs()
            patchFile.writeText(patch)
            println("Patch with ${edits.size} edit(s) written to ${patchFile.path}")
            println("Apply with:  git apply ${patchFile.relativeTo(repoRoot).path}")
        }
        println("\nFixer summary:\n$summary")
    }

    private fun applyToWorkingTree() {
        edits.groupBy { it.path }.forEach { (path, _) ->
            val file = repoRoot.resolve(path)
            val updated = contentWithEdits(path, file.readText())
                ?: error("Edit conflict in $path — aborting without writing")
            file.writeText(updated)
        }
    }

    /** Generate a git-appliable unified diff ourselves (never trust LLM line numbers). */
    private fun generatePatch(): String {
        val tmp = File(repoRoot, "build/.prodcheck-tmp").apply { deleteRecursively(); mkdirs() }
        val sb = StringBuilder()
        edits.groupBy { it.path }.forEach { (path, _) ->
            val original = repoRoot.resolve(path)
            val updated = contentWithEdits(path, original.readText())
                ?: error("Edit conflict in $path")
            val tmpFile = tmp.resolve(path).apply { parentFile.mkdirs(); writeText(updated) }

            val proc = ProcessBuilder(
                "git", "diff", "--no-index",
                "--src-prefix=a/", "--dst-prefix=b/",
                path, tmpFile.relativeTo(repoRoot).path
            ).directory(repoRoot).redirectErrorStream(true).start()
            val raw = proc.inputStream.bufferedReader().readText()
            proc.waitFor()

            // Rewrite the tmp path in headers so `git apply` targets the real file.
            sb.append(raw.replace("b/build/.prodcheck-tmp/$path", "b/$path"))
        }
        tmp.deleteRecursively()
        return sb.toString()
    }
}
